[package]
name = "anecho-client"
description = "Rust client for the Anecho WebSocket API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anecho-contract.workspace = true
anecho-wire.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
thiserror.workspace = true
log.workspace = true

[lints]
workspace = true
